name: rwkv_studio
description: "RWKV Studio"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  rwkv_dart:
    path: ../rwkv_dart

  dio: ^5.0.0
  rxdart: ^0.28.0
  font_awesome_flutter: ^10.8.0
  flutter_midi_command: ^0.5.3
  xmidi:
    path: ../xmidi

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true