name: rwkv_studio
description: "RWKV Studio"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

 # rwkv_libs:
   # path: ../rwkv_libs

  rwkv_dart:
    path: ../rwkv_dart
#    git:
#      url: https://github.com/RWKV-APP/rwkv_dart.git
#      ref: dev

  rwkv_downloader:
    path: ../rwkv_downloader
#    git:
#      url: https://github.com/RWKV-APP/rwkv_downloader.git
#      ref: dev
  rwkv_libs:
    path: ../rwkv_libs

  flutter_bloc: ^9.1.1
  dio: ^5.0.0
  rxdart: ^0.28.0
  font_awesome_flutter: ^10.8.0
  window_manager: ^0.5.1
  #  file_selector: ^1.0.3
  path_provider: ^2.1.5
  just_audio: ^0.10.5
  just_audio_windows:
  just_audio_media_kit:
  media_kit_libs_windows_audio:
  url_launcher: ^6.3.2
  desktop_drop: ^0.7.0
  crypto: ^3.0.6
  fluent_ui: ^4.13.0
  logging: ^1.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansSC
      fonts:
        - asset: fonts/NotoSansSC-Regular.ttf
        - asset: fonts/NotoSansSC-ExtraLight.ttf
          weight: 300
        - asset: fonts/NotoSansSC-SemiBold.ttf
          weight: 700