name: rwkv_studio
description: "RWKV Studio"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  rwkv_flutter:
    path: ../rwkv_flutter

  dio: ^5.0.0
  rxdart: ^0.28.0
  path_provider: ^2.1.5
  font_awesome_flutter: ^10.8.0
  cupertino_icons: ^1.0.8
  file_selector: any
  objectbox: ^4.3.0
  objectbox_flutter_libs: any
  onnxruntime: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  objectbox_generator: any

flutter:
  uses-material-design: true